# Site settings
title: Hussein Lezzaik blog
email: 
description: "Musings of a Roboticist."
baseurl: ""
url: "http://husseinlezzaik.github.io"
github_username:  HusseinLezzaik

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
